name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main # Change this to your main branch name

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22' # Specify the Node.js version your project uses

      - name: Install Dependencies
        run: npm ci

      - name: Build Project
        run: npm run dev # Your project's build command

      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_PLACEMENTPREP }}' # Use your secret name
          projectId: 'placementprep-e01d8' # Your Firebase Project ID
          channelId: 'live'